// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ASfP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;

    /// <summary>
    /// Extension methods for Asfpfunc.
    /// </summary>
    public static partial class AsfpfuncExtensions
    {
            /// <summary>
            /// Replace with Operation Object
            /// #http://swagger.io/specification/#operationObject
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static void ApipFuncpost(this IAsfpfunc operations)
            {
                Task.Factory.StartNew(s => ((IAsfpfunc)s).ApipFuncpostAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Replace with Operation Object
            /// #http://swagger.io/specification/#operationObject
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task ApipFuncpostAsync(this IAsfpfunc operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.ApipFuncpostWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false);
            }

    }
}
